# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: connector_service_definition/connector.proto for package 'grpc'

require 'grpc'
require_relative 'connector_pb'

module Grpc
  module Connector
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'grpc.Connector'

      rpc :triggers, TriggersRequest, TriggersResponse
      # used by Workflows to get triggers defined by the Connector. Run when a user registers or refreshes a Connector.
      rpc :perform_trigger, TriggerRequest, TriggerResponse
      # used by Workflows to check for trigger events. Polled periodically.
      rpc :actions, ActionsRequest, ActionsResponse
      # used by Workflows to get get actions defined by the Connector. Run when a user registers or refreshes a Connector.
      rpc :perform_action, ActionRequest, ActionResponse
      # used by Workflows to perform an action defined by the Connector. Run when a Workflow containing the defined action is run.
    end

    Stub = Service.rpc_stub_class
  end
end
