# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connector_service_definition/connector.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("connector_service_definition/connector.proto", :syntax => :proto3) do
    add_message "grpc.Action" do
      optional :display_name, :string, 1
      optional :description, :string, 2
      repeated :inputs, :message, 3, "grpc.Field"
      repeated :outputs, :message, 4, "grpc.Field"
    end
    add_message "grpc.ActionRequest" do
      optional :action, :message, 1, "grpc.Action"
      map :params, :string, :string, 2
    end
    add_message "grpc.ActionResponse" do
      optional :status, :enum, 1, "grpc.ActionResponse.Status"
      map :outputs, :string, :string, 2
    end
    add_enum "grpc.ActionResponse.Status" do
      value :SUCCESS, 0
      value :ERROR, 1
      value :HALT, 2
    end
    add_message "grpc.Trigger" do
      optional :display_name, :string, 1
      optional :type, :string, 2
      optional :app_key, :string, 3
      repeated :outputs, :message, 4, "grpc.Field"
      optional :description, :string, 5
    end
    add_message "grpc.TriggerRequest" do
      optional :trigger, :message, 1, "grpc.Trigger"
      map :params, :string, :string, 2
    end
    add_message "grpc.TriggerResponse" do
      optional :status, :enum, 1, "grpc.TriggerResponse.Status"
      optional :error_message, :string, 2
      repeated :events, :message, 3, "grpc.Event"
    end
    add_enum "grpc.TriggerResponse.Status" do
      value :SUCCESS, 0
      value :ERROR, 1
    end
    add_message "grpc.ActionsRequest" do
    end
    add_message "grpc.ActionsResponse" do
      repeated :actions, :message, 1, "grpc.Action"
    end
    add_message "grpc.TriggersRequest" do
    end
    add_message "grpc.TriggersResponse" do
      repeated :triggers, :message, 1, "grpc.Trigger"
    end
    add_message "grpc.Field" do
      optional :display_name, :string, 1
      optional :key, :string, 2
      optional :type, :string, 3
      optional :app_key, :string, 6
      optional :description, :string, 4
      optional :required, :bool, 5
    end
    add_message "grpc.Event" do
      optional :payload, :string, 1
    end
  end
end

module Grpc
  Action = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.Action").msgclass
  ActionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.ActionRequest").msgclass
  ActionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.ActionResponse").msgclass
  ActionResponse::Status = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.ActionResponse.Status").enummodule
  Trigger = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.Trigger").msgclass
  TriggerRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.TriggerRequest").msgclass
  TriggerResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.TriggerResponse").msgclass
  TriggerResponse::Status = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.TriggerResponse.Status").enummodule
  ActionsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.ActionsRequest").msgclass
  ActionsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.ActionsResponse").msgclass
  TriggersRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.TriggersRequest").msgclass
  TriggersResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.TriggersResponse").msgclass
  Field = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.Field").msgclass
  Event = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.Event").msgclass
end
